### ISSUE TITLE
[docs] 언급 주신 feature list에 대하여

### ISSUE THREAD

**Issue by Sinyoung3016** [Sinyoung3016/BreakPurdue#2]
* 만들어주신 feature list를 notion에 정리해서, 해당 notion 링크를 readme에 올리는 방식은 어떠할까요?
* readme의 주요 기능 파트에는 개발 후 간단한 시연 gif를 넣으려고 하는데 이 방식에 대한 의견도 궁금합니다!

**Comment by qkrdmstlr3** [comment]
- 개인적으로는 노션(계획/회의) 따로 피그마(디자인) 따로 기능목록(진행상황) 따로해서 모두 리드미에 작성하는 것이 어떨까합니다. 노션에 통합해버리면 외부에서 링크하나만 보고는 어떤 산출물이 있는지 짐작하기 힘들 것 같아서요(두번 링크타고 들어가야하기도하고). 마크다운으로 링크들을 깔끔하게 정리하면 어떨까요?
- 좋습니다!

**Comment by Sinyoung3016** [comment]
- 좋아요! 말씀주신 대로, 정리하겠습니다!
